name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: teatimeguest/setup-texlive-action@v2.4.1
        with:
          package-file: DEPENDS.txt
          packages: scheme-basic xetex ffcode libertine microtype hypdoc l3build href-ul newtx
      - run: ls -al
      - run: pdflatex phi.ins
      - run: pdflatex --shell-escape phi.dtx
      - run: l3build ctan --show-log-on-error --halt-on-error
  publish:
    runs-on: ubuntu-20.04
    needs: l3build
    if: github.ref == 'refs/heads/master'
    steps:
      - run: mkdir gh-pages && cp build/local/* gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
